"""The three systems under comparison (blueprint section 8.1).

    A. Direct LLM        question, design card, schema and the *same* fixed
                         summary statistics System C receives at step 1; no tools.
    B. LLM with tools     identical tool definitions and report schema; an
                         unconstrained loop, no ordered protocol.
    C. Structured agent   the same tools plus the state machine, routing policy,
                         one permitted revision, and the verifier.

Fairness (review finding F-C1): A's evidence dump is generated by the same
``_gather_evidence`` call C uses, not by a hand-picked digest.  B receives
``ToolRegistry.specs()`` verbatim.  Only the driver differs.
"""
from __future__ import annotations

import json
import time

from aistat.agents.base import Case, DriverBase, RunResult
from aistat.agents.contracts import INSTRUCTIONS, SCHEMAS, normalise
from aistat.agents.reporting import compose_report
from aistat.schemas.core import ABSTAIN, REF_PATTERN

MAX_TOOL_STEPS = 12
MAX_REVISIONS = 1


def _validate_report(report: dict | None, store) -> str | None:
    """Return a corrective message if the report is unusable, else None."""
    if not report:
        return ("Your response did not parse as the required JSON object. "
                "Return only the object, with all six sections.")
    from aistat.schemas.core import FinalReport, find_raw_numbers
    problems: list[str] = []

    for name in ("problem_statement", "data_audit", "method_decision",
                 "results", "interpretation", "limitations"):
        text = (report.get(name) or {}).get("text", "")
        for lit in find_raw_numbers(text):
            problems.append(
                f"In `{name}` you wrote the literal number {lit}. Replace it "
                "with the {{reference}} whose value it is, or remove the claim.")
        for m in REF_PATTERN.finditer(text):
            ref = m.group(1)
            if ref not in store:
                near = store.nearest(ref)
                hint = f" Closest available: {', '.join(near[:3])}." if near else ""
                problems.append(
                    f"In `{name}` the reference {{{{{ref}}}}} does not exist.{hint}")
    if not problems:
        return None
    return ("Your report was rejected. Fix exactly these problems and return "
            "the corrected object:\n- " + "\n- ".join(problems[:8]))


def _ask(client, *, system: str, case: Case, purpose: str, context: dict,
         evidence: dict | None = None, refs: list[str] | None = None,
         trace=None, extra: str | None = None):
    """One decision-point call.

    Carries the schema and the instruction the live path needs, and normalises
    the response back into the shape the drivers consume.  The offline client
    ignores both and answers from ``context``; that asymmetry is deliberate and
    is why this helper is the only place either is assembled.
    """
    instruction = INSTRUCTIONS.get(purpose)
    if extra:
        instruction = f"{instruction}\n\n{extra}" if instruction else extra
    msgs = _msgs(case, evidence, instruction=instruction, available_refs=refs)
    resp = client.complete(system=system, messages=msgs,
                           output_schema=SCHEMAS.get(purpose),
                           purpose=purpose, context=context)
    if trace is not None:
        trace.llm(purpose, resp)
    return resp, normalise(purpose, resp.structured)


# ==========================================================================
# System A -- direct LLM advice, no tools
# ==========================================================================


class DirectDriver(DriverBase):
    system_name = "A_direct"

    def run(self, case: Case, rep: int = 0) -> RunResult:
        t0 = time.perf_counter()
        run_id, store, registry, trace = self._new_run(case, rep)
        trace.state("start", system=self.system_name)
        task = self._task(case)

        # The identical evidence System C sees at step 1 -- see F-C1.
        trace.state("evidence_dump")
        evidence, refs, slot_ids = self._gather_evidence(registry, task, trace)

        ctx = self._ctx(case, store, registry, evidence=evidence,
                        slot_ids=slot_ids,
                        evidence_refs=list(store.keys())[:40])
        trace.state("advise")
        resp, sel = _ask(self.client, system=_SYSTEM_A, case=case,
                         purpose="direct_advice", context=ctx, evidence=evidence,
                         refs=list(store.keys())[:60], trace=trace)
        sel = sel or {"method": ABSTAIN, "abstain_reason": None}
        sel.setdefault("evidence_refs", [])
        sel.setdefault("rejected_alternatives", {})
        sel.setdefault("confidence", "moderate")

        # A recommends but does not execute: no result reference exists.
        report = compose_report({**ctx, "selection": sel, "result_call_id": None,
                                 "diagnostic_refs": refs})
        report["results"] = {"text": (
            "No method was executed, so no estimate, interval or effect size is "
            "reported. The recommendation above is advisory.")}
        trace.state("done")
        return self._finalise(case=case, run_id=run_id, rep=rep, store=store,
                              registry=registry, trace=trace, report_dict=report,
                              selection=sel, t0=t0, n_llm=1)


# ==========================================================================
# System B -- tools, no protocol
# ==========================================================================


class ToolLoopDriver(DriverBase):
    """Unconstrained tool loop.

    Deliberately written as the thinnest possible wrapper around the model's own
    tool use, so no reviewer can claim the baseline's control flow was authored
    to lose.  On the live path this is the SDK's tool-runner behaviour.
    """

    system_name = "B_tools"

    def run(self, case: Case, rep: int = 0) -> RunResult:
        t0 = time.perf_counter()
        run_id, store, registry, trace = self._new_run(case, rep)
        trace.state("start", system=self.system_name)
        task = self._task(case)

        messages = _msgs(case, None)
        called: list[str] = []
        evidence: dict = {}
        slot_ids: dict[str, str] = {}
        result_call_id = None
        n_llm = 0

        for step in range(MAX_TOOL_STEPS):
            ctx = self._ctx(case, store, registry, step=step, called=called,
                            evidence=evidence, slot_ids=slot_ids)
            resp = self.client.complete(
                system=_SYSTEM_B, messages=messages,
                tools=registry.specs(strict=True),
                purpose="free_tool_use", context=ctx)
            n_llm += 1
            trace.llm("free_tool_use", resp)
            if not resp.wants_tools:
                break

            # The API pairs a tool_result with the tool_use that requested it,
            # by id, in a single following user message.  Splitting results
            # across messages -- or paraphrasing them as text -- breaks the
            # pairing and silently trains the model out of parallel tool use.
            assistant_blocks: list[dict] = []
            if resp.text:
                assistant_blocks.append({"type": "text", "text": resp.text})
            result_blocks: list[dict] = []

            for tu in resp.tool_uses:
                tc = registry.call(tu.name, tu.input)
                trace.tool(tc.call_id, tc.name, tc.arguments, tc.is_error,
                           len(tc.payload) if isinstance(tc.payload, dict) else 0)
                called.append(tu.name)
                if not tc.is_error:
                    for key, slot in (("summarize_groups", "summary"),
                                      ("check_group_assumptions", "assumptions"),
                                      ("check_contingency", "contingency"),
                                      ("check_association", "association"),
                                      ("inspect_dataset", "inspect")):
                        if tu.name == key:
                            evidence[slot] = tc.payload
                            slot_ids[slot] = tc.call_id
                    if tu.name in ("run_group_test", "run_categorical_or_correlation",
                                   "fit_regression"):
                        result_call_id = tc.call_id
                        evidence["dispersion"] = tc.payload
                assistant_blocks.append({"type": "tool_use", "id": tu.id,
                                         "name": tu.name, "input": tu.input})
                result_blocks.append({
                    "type": "tool_result", "tool_use_id": tu.id,
                    "content": json.dumps(tc.payload, default=str)[:6000],
                    **({"is_error": True} if tc.is_error else {}),
                })

            if assistant_blocks and result_blocks:
                messages = messages + [
                    {"role": "assistant", "content": assistant_blocks},
                    {"role": "user", "content": result_blocks},
                ]

        method = (registry.executed_methods or [ABSTAIN])[-1]
        sel = {"method": method, "abstain_reason": None, "evidence_refs": [],
               "rejected_alternatives": {}, "confidence": "moderate",
               "_rationale": "Selected during unconstrained tool use."}
        ctx = self._ctx(case, store, registry, evidence=evidence,
                        slot_ids=slot_ids,
                        evidence_refs=list(store.keys())[:40])
        report = compose_report({**ctx, "selection": sel,
                                 "result_call_id": result_call_id,
                                 "diagnostic_refs": {}})
        trace.state("done")
        return self._finalise(case=case, run_id=run_id, rep=rep, store=store,
                              registry=registry, trace=trace, report_dict=report,
                              selection=sel, t0=t0, n_llm=n_llm)


# ==========================================================================
# System C -- the structured statistical agent
# ==========================================================================


class ProtocolDriver(DriverBase):
    """Deterministic state machine (blueprint section 6 step 9).

    parse -> validate design -> enumerate candidates -> request targeted
    diagnostics -> select or abstain -> execute -> diagnose -> revise once ->
    verify -> report.  The model supplies semantic judgement at the marked
    points; it can never bypass design validation or invent a number.
    """

    system_name = "C_protocol"

    def run(self, case: Case, rep: int = 0) -> RunResult:
        t0 = time.perf_counter()
        run_id, store, registry, trace = self._new_run(case, rep)
        trace.state("start", system=self.system_name)
        task = self._task(case)
        n_llm = 0
        revised = False

        # 1 -- parse the problem ------------------------------------------
        trace.state("parse_problem")
        ctx = self._ctx(case, store, registry)
        _, spec = _ask(self.client, system=_SYSTEM_C, case=case,
                       purpose="parse_problem", context=ctx, trace=trace)
        spec = spec or {}
        n_llm += 1
        trace.state("analysis_spec", estimand=spec.get("estimand"),
                    hazards=spec.get("design_hazards"))

        # 2 -- enumerate candidates (design validity gates this) ----------
        trace.state("plan_candidates")
        _, plan = _ask(self.client, system=_SYSTEM_C, case=case,
                       purpose="plan_candidates", context={**ctx, "spec": spec},
                       evidence={"analysis_spec": spec}, trace=trace)
        plan = plan or {}
        n_llm += 1
        trace.state("candidate_plan", eligible=plan.get("eligible_methods"))

        # 3 -- targeted diagnostics ---------------------------------------
        evidence: dict = {}
        refs: dict[str, str] = {}
        slot_ids: dict[str, str] = {}
        if plan.get("eligible_methods") != [ABSTAIN]:
            trace.state("request_diagnostics")
            evidence, refs, slot_ids = self._gather_evidence(registry, task, trace)
        else:
            tc = registry.call("inspect_dataset")
            trace.tool(tc.call_id, tc.name, tc.arguments, tc.is_error, len(tc.payload))
            if not tc.is_error:
                evidence["inspect"] = tc.payload
                refs["n_rows"] = f"{tc.call_id}.n_rows"

        # 4 -- select or abstain ------------------------------------------
        trace.state("select_method")
        sel_ctx = {**ctx, "spec": spec, "plan": plan, "evidence": evidence,
                   "slot_ids": slot_ids,
                   "evidence_refs": list(store.keys())[:40]}
        _, sel = _ask(self.client, system=_SYSTEM_C, case=case,
                      purpose="select_method", context=sel_ctx, evidence=evidence,
                      refs=store.keys(), trace=trace)
        sel = sel or {"method": ABSTAIN, "abstain_reason": "missing_design_facts"}
        n_llm += 1
        trace.state("selection", method=sel.get("method"),
                    reason=sel.get("abstain_reason"))

        # 5 -- execute + model diagnostics --------------------------------
        result_call_id = None
        if sel.get("method") != ABSTAIN:
            trace.state("execute", method=sel["method"])
            tc = self._execute(registry, sel["method"], task, trace)
            if not tc.is_error:
                result_call_id = tc.call_id
                evidence["dispersion"] = tc.payload

                # 6 -- one permitted revision (blueprint section 7) --------
                new_method = _revision(sel["method"], tc.payload)
                if new_method:
                    revised = True
                    trigger = _revision_trigger(sel["method"], tc.payload, tc.call_id)
                    trace.state("revise", frm=sel["method"], to=new_method,
                                trigger=trigger)
                    tc2 = self._execute(registry, new_method, task, trace)
                    if not tc2.is_error:
                        sel["rejected_alternatives"] = {
                            **(sel.get("rejected_alternatives") or {}),
                            sel["method"]: trigger,
                        }
                        sel["method"] = new_method
                        sel["_rationale"] = (
                            str(sel.get("_rationale", "")) + " After fitting, "
                            + trigger + " prompted one permitted revision.")
                        result_call_id = tc2.call_id
            else:
                trace.error("execute", str(tc.payload.get("error")))

        # 7 -- report ------------------------------------------------------
        trace.state("write_report")
        rep_ctx = {**ctx, "selection": sel, "result_call_id": result_call_id,
                   "diagnostic_refs": refs, "evidence": evidence,
                   "slot_ids": slot_ids,
                   "evidence_refs": list(store.keys())[:40]}
        citable = store.citable()
        _, report = _ask(self.client, system=_SYSTEM_C, case=case,
                         purpose="write_report", context=rep_ctx, evidence=evidence,
                         refs=citable, trace=trace)
        n_llm += 1

        # One corrective retry, quoting the exact violation back.  A report that
        # cites a reference that does not exist, or writes a bare number, is a
        # recoverable slip -- failing the whole run for it would depress System
        # C's measured accuracy for reasons that have nothing to do with
        # statistics.  Bounded at one attempt, and counted so it is reportable.
        correction = _validate_report(report, store)
        report_retried = False
        if correction:
            trace.state("report_rejected", detail=correction[:300])
            _, retry = _ask(self.client, system=_SYSTEM_C, case=case,
                            purpose="write_report", context=rep_ctx,
                            evidence=evidence, refs=citable, trace=trace,
                            extra=correction)
            n_llm += 1
            report_retried = True
            if retry and _validate_report(retry, store) is None:
                report = retry
                trace.state("report_corrected")
            else:
                trace.state("report_still_invalid")
        if report:
            report.setdefault("case_id", case.case_id)
            report.setdefault("selection",
                              {k: v for k, v in sel.items() if not k.startswith("_")})
            report.setdefault("trace_ids", list(store.keys())[:8])
        else:
            report = compose_report(rep_ctx)

        trace.state("done")
        return self._finalise(case=case, run_id=run_id, rep=rep, store=store,
                              registry=registry, trace=trace, report_dict=report,
                              selection=sel, t0=t0, revised=revised, n_llm=n_llm,
                              metadata={"report_retried": report_retried})


# --------------------------------------------------------------------------
# Revision rule
# --------------------------------------------------------------------------


def _revision(method: str, payload: dict) -> str | None:
    """At most one post-fit revision, and only on a material diagnostic failure."""
    if method == "poisson" and payload.get("overdispersion_flag"):
        return "negative_binomial"
    if method == "student_t" and payload.get("effect_size", {}).get("name") == "hedges_g":
        return None
    return None


def _revision_trigger(method: str, payload: dict, call_id: str | None = None) -> str:
    """Explain the revision, citing the diagnostic by reference not by literal.

    The provenance contract covers decision prose as well as results, so this
    string must never contain a formatted number.
    """
    if payload.get("overdispersion_flag"):
        if call_id:
            return (f"a conditional Pearson dispersion of "
                    f"{{{{{call_id}.pearson_dispersion}}}} exceeded the Poisson "
                    "mean-variance identity")
        return "conditional dispersion exceeded the Poisson mean-variance identity"
    return "a material diagnostic failure"


# --------------------------------------------------------------------------
# Prompts
# --------------------------------------------------------------------------


def _msgs(case: Case, evidence: dict | None, instruction: str | None = None,
          available_refs: list[str] | None = None) -> list[dict]:
    parts = [
        f"Question: {case.question}",
        f"Analysis objective: {case.objective}",
        f"Design card:\n{json.dumps(case.card, indent=2)}",
        f"Variable roles:\n{json.dumps(case.roles, indent=2)}",
        f"Data schema: {len(case.df)} rows, columns "
        f"{list(case.df.columns)}",
    ]
    if evidence:
        parts.append("Diagnostic evidence:\n"
                     + json.dumps(evidence, default=str)[:12000])
    if available_refs:
        # The exact set of citable references, split by kind.  The first pilot
        # showed the model inventing plausible siblings of real keys
        # (effect_size.value -> effect_size.interpretation), so the catalogue is
        # exhaustive and explicitly closed.
        numeric = [r for r in available_refs if not r.endswith(
            ("interpretation", "name", "method", "_flag", "estimate_label",
             "_note", "_label"))]
        labels = [r for r in available_refs if r not in numeric]
        block = ["Available references. Cite ONLY these, exactly as written, "
                 "each wrapped as {{reference}}. Any other reference fails the "
                 "run -- do not invent variants of these names."]
        block.append(f"\nNumeric ({len(numeric)}):\n" + "\n".join(numeric))
        if labels:
            block.append(f"\nQualitative ({len(labels)}):\n" + "\n".join(labels))
        parts.append("\n".join(block))
    if instruction:
        parts.append("TASK: " + instruction)
    return [{"role": "user", "content": "\n\n".join(parts)}]


_SHARED_POLICY = """\
Supported methods (the library is closed -- nothing outside it may be selected):
  two independent groups   student_t, welch_t, mann_whitney
  three or more groups     one_way_anova, welch_anova, kruskal_wallis
  two categorical          chi_square, fisher_exact
  two continuous/ordinal   pearson, spearman
  regression               ols, logistic, poisson, negative_binomial
If no supported method is valid for the design, the correct answer is "abstain".

Reporting contract: you may not write any number. Every statistic, interval,
effect size and count must appear as a {{tool_result_reference}} template, for
example {{r3.welch_t.p_value}}. References are substituted from recorded tool
output; an unknown reference fails the run."""

_SYSTEM_A = f"""You are a statistical adviser. You are given a question, a design
card, a data schema and a fixed set of summary statistics. You have no tools and
cannot execute anything. Recommend the single most appropriate method and explain
the reasoning.

{_SHARED_POLICY}"""

_SYSTEM_B = f"""You are a statistical analyst with access to validated tools. Use
them however you judge best, then report the result.

{_SHARED_POLICY}"""

_SYSTEM_C = f"""You are a statistical analyst operating under an explicit decision
protocol. The sequence is fixed: parse the problem, validate the design, enumerate
candidate methods, request only the diagnostics that could change the decision,
select or abstain, execute, check model diagnostics, revise at most once, report.

Decision principles:
1. Design validity precedes distribution checks. Dependence, pairing, clustering
   and time order invalidate every in-scope method regardless of variable types.
2. Assumption tests are evidence, not switches. Weigh group size, spread, skew,
   Q-Q behaviour and influence together.
3. Welch is the default when variances differ or groups are unbalanced. Student
   requires an affirmative equal-variance justification.
4. Rank tests describe stochastic ordering, not medians.
5. Pearson for an approximately linear relationship without dominant points;
   Spearman for monotone or ordinal relationships.
6. Poisson versus negative binomial is decided from conditional dispersion after
   fitting, never from the marginal variance alone.
7. When a material design fact is unknown, ask or abstain.

{_SHARED_POLICY}"""


SYSTEMS = {
    "A_direct": DirectDriver,
    "B_tools": ToolLoopDriver,
    "C_protocol": ProtocolDriver,
}
